// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Node interface {
	IsNode()
	GetID() string
}



type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
